name: Store Changed Files
description: 'Returns changed GPML file name'

outputs:
  changed_gpml_file_name:
    description: "Name of new RDF file genereted"
    value: ${{ steps.changes.outputs.gpml }}

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Get changed files
      id: changes
      run: |
        echo "::set-output name=gpml::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep .gpml$ | xargs)"
      shell: bash
    - name: Set GitHub Action Path
      run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
